import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# ENABLE TERMINAL COLORS
[env]
TERM = "xterm-256color"


# WINDOW PADDING
[window]
padding.x = 10
padding.y = 10

# WINDOW BUTTONS
decorations = "Buttonless"

# TRANSPARENCY
opacity = 0.1

# BLUR
blur = true


# FONT CONFIGS
[font]
size = 14.0

[font.bold]
# family = "Hack Nerd Font Mono"
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "Hack Nerd Font Mono"
family = "Hack Nerd Font"
style = "Regular"




